const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
function read(relative) {
  return fs.readFileSync(path.join(root, relative), 'utf8')
}

const manifest = JSON.parse(read('manifest.json'))
assert.equal(manifest.schemaVersion, 1)
assert.equal(manifest.id, 'mpb.workspace-overview')
assert.deepEqual(manifest.kinds, ['overlay'])
assert.equal(manifest.entryPoints.overlay, 'Overview.qml')
assert.match(read('LICENSE'), /MIT License/)

const overlay = read('Overview.qml')
assert.match(overlay, /^Item \{/m)
assert.match(overlay, /function open\(payloadJson\)/)
assert.match(overlay, /function close\(\)/)
assert.match(overlay, /function toggle\(\)/)
assert.match(overlay, /property bool opened/)
assert.match(overlay, /shell\.hide\(/)
assert.match(overlay, /visible: root\.opened/)
assert.match(overlay, /WlrLayershell\.keyboardFocus: root\.opened \? WlrKeyboardFocus\.Exclusive : WlrKeyboardFocus\.None/)
assert.match(overlay, /WlrLayershell\.layer: WlrLayer\.Overlay/)
assert.match(overlay, /exclusionMode: ExclusionMode\.Ignore/)
assert.match(overlay, /Qt\.Key_Escape/)
assert.match(overlay, /Qt\.Key_PageDown/)
assert.match(overlay, /Qt\.Key_J/)
assert.match(overlay, /workspaceIdFromDigit/)
assert.match(overlay, /workspaceIdFromKeyCode/)
assert.match(overlay, /occupiedWorkspaceIds/)
assert.match(overlay, /GRID_COLUMNS/)
assert.match(overlay, /if \(request === ""\) return/)
assert.match(overlay, /Hyprland\.dispatch\(request\)/)
assert.doesNotMatch(overlay, /\bProcess\s*\{/)
assert.doesNotMatch(overlay, /execDetached|bash -c|sh -c|hyprctl/)
assert.match(overlay, /import qs\.Commons/)
assert.match(overlay, /import qs\.Ui/)
assert.doesNotMatch(overlay, /#[0-9a-fA-F]{6}/)
assert.match(overlay, /entering|mapScale/)
assert.doesNotMatch(overlay, /\bFlickable\b/)
assert.match(overlay, /id: scroller/)
assert.match(overlay, /y: -scroller\.contentY/)
assert.match(overlay, /OverviewModel\.revealScrollY/)
assert.match(overlay, /OverviewModel\.stepScrollY/)
assert.match(overlay, /OverviewModel\.wheelDelta/)
assert.match(overlay, /WheelArea/)
assert.doesNotMatch(overlay, /mask:\s*Region/)

const tile = read('WorkspaceTile.qml')
assert.match(tile, /OverviewModel\.layoutWindows/)
assert.match(tile, /WindowThumb/)
assert.match(tile, /WheelArea/)
assert.match(tile, /Image \{/)
assert.match(tile, /current\/background/)
assert.match(tile, /PreserveAspectCrop/)
assert.doesNotMatch(tile, /#[0-9a-fA-F]{6}/)

const thumb = read('WindowThumb.qml')
assert.match(thumb, /ScreencopyView \{/)
assert.match(thumb, /captureSource:/)
assert.match(thumb, /live:/)
assert.match(thumb, /WheelArea/)
assert.doesNotMatch(thumb, /#[0-9a-fA-F]{6}/)

const wheel = read('WheelArea.qml')
assert.match(wheel, /MouseArea/)
assert.match(wheel, /onWheel/)

console.log('ok - workspace overview contract')
